version: '2'
services:
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
    - "25"
    env_file:
      - stack.env
    restart: always
    ports:
      - 9025:25
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
